apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
        - name: mysql-init
          image: mysql:5.7
          command: ["/bin/sh", "-c"]
          args:
            - |
              sleep 10; # Attendre que MySQL soit prêt
              mysql -h mysql-service -u root -p$MYSQL_ROOT_PASSWORD <<EOF
              CREATE DATABASE IF NOT EXISTS users_db;
              USE users_db;
              CREATE TABLE IF NOT EXISTS users (
                id INT AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(255),
                email VARCHAR(255)
              );
              INSERT INTO users (name, email) VALUES
                ('Alice', 'alice@example.com'),
                ('Bob', 'bob@example.com');
              EOF
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
      restartPolicy: Never
